# Nandini Garg
# E20CSE487
# EB32

PART A

In [1]:
import numpy as np
import sys
print(np.__version__)

1.21.6


In [2]:
arr = np.random.randint(5, size=(1,5))
new_array = np.random.randint(5, size=(5,5))
print(new_array)
print(new_array.shape)
print(type(new_array))
print(arr)
print(arr.shape)
print(type(arr))

[[3 1 3 4 4]
 [0 3 0 3 2]
 [4 2 0 2 3]
 [4 3 4 3 3]
 [3 0 4 2 1]]
(5, 5)
<class 'numpy.ndarray'>
[[2 2 4 2 4]]
(1, 5)
<class 'numpy.ndarray'>


In [3]:
N = np.array([4, 5, 6, 3, 9, 7])
print(N)
print(N[2:5])

[4 5 6 3 9 7]
[6 3 9]


In [4]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(array2d[0,0:2])

[1 2]


In [5]:
arr1 = np.array( [4,5,6,7])
arr2 = np.array( [3,4,1])
fin = np.concatenate((arr1,arr2),axis = 0)
print(fin)

[4 5 6 7 3 4 1]


In [6]:
arr1 = np.array([[1,2,3],[4,5,6]])
print("First: ",arr1)
arr2 = np.array([[7,8,9],[10,11,12]])
print("Second: ",arr2)
print("result")
print(np.concatenate((arr1,arr2)))


First:  [[1 2 3]
 [4 5 6]]
Second:  [[ 7  8  9]
 [10 11 12]]
result
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
sArr = np.array([4, 5, 6, 3, 9,8])
print(sArr)
print(np.split(sArr,[2,3]))
print()
array2d =  np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])

print(np.hsplit(array2d,[2,3]))

[4 5 6 3 9 8]
[array([4, 5]), array([6]), array([3, 9, 8])]

[array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]]), array([], shape=(4, 0), dtype=int64)]


In [8]:
ar = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(ar == 4))

ar2d = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
print(np.where(ar2d == 5))

(array([3, 5, 6]),)
(array([1]), array([1]))


In [9]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
odd = np.where(b%2==0)
even = np.where(b%2==1)
print("Even:",even,"Odd:", odd)

Even: (array([0, 2, 4, 6]),) Odd: (array([1, 3, 5, 7]),)


In [10]:
ar1d = np.array([6, 5, 1, 2, 9, 10, 36, 7])
print('ascending order', np.sort(ar1d))
print('descending order', np.sort(ar1d)[::-1])

ar2d = np.array([[5, 3, 7], [8, 10, 6], [40, -2, 7]])
print('ascending order', np.sort(ar2d))
print('descending order', np.sort(ar2d)[::-1])

ascending order [ 1  2  5  6  7  9 10 36]
descending order [36 10  9  7  6  5  2  1]
ascending order [[ 3  5  7]
 [ 6  8 10]
 [-2  7 40]]
descending order [[-2  7 40]
 [ 6  8 10]
 [ 3  5  7]]


In [11]:
import random
ran = np.random.randint(21 , size = (6))
print(ran)
ranF = np.random.rand(5) 
print(ranF)

ran2d = np.random.randint(50, size = (3,5))
print(ran2d)

random2d = np.random.rand(3,5)
print(random2d)

[ 7 14 18  6 13  4]
[0.06842311 0.38231606 0.33717967 0.88656052 0.88888486]
[[ 7 40 13 25 39]
 [16 19 33 19 19]
 [10 31 18 37 11]]
[[0.53456904 0.40026681 0.77812573 0.24190473 0.23280121]
 [0.95851271 0.73103993 0.9775832  0.8819516  0.33375303]
 [0.06332715 0.04197915 0.68940916 0.1135188  0.93875764]]


In [12]:
A = np.array([[ 1, 2, 3],[ 4, 5, 6],[ 7, 8, 9],[10, 11, 12]])
np.random.shuffle(A)
print(A)

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]



Part B

In [14]:
import pandas as pd
from scipy import stats as st
import matplotlib.pyplot as plt

In [22]:
wines = pd.read_csv('/content/winequality-red.csv', sep=";")
wines.head()


fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"
7.4  0.70 0.00 1.9 0.076 11.0 34.0 0.9978 3.51 0.56 9.4                                                  5                                                                                                                      
7.8  0.88 0.00 2.6 0.098 25.0 67.0 0.9968 3.20 0.68 9.8                                                  5                                                                                                                      
     0.76 0.04 2.3 0.092 15.0 54.0 0.9970 3.26 0.65 9.8                                                  5                                                                                                                      
11.2 0.28 0.56 1.9 0.075 17.0 60.0 0.9980 3.16 0.58 9.8                                                  6                                                                                                                      
7.4  0.70 0.00 1.9 0.076 11.0 34.0 0.9978 3.51 0.56 9.4                                                  5

In [28]:
planeXY = wines.values
print(planeXY)
planeXY.shape

#converted to 2d array

[[5]
 [5]
 [5]
 ...
 [6]
 [5]
 [6]]


(1599, 1)

In [26]:
wines.shape

(1599, 1)

In [41]:
# slicing the matrix from XY matrix
# X=wines['quality'].to_numpy()
Y = wines.iloc[:,-1]
X = wines.iloc[:, 0:11]
Y.head()

7.4   0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4    5
7.8   0.88  0.00  2.6  0.098  25.0  67.0  0.9968  3.20  0.68  9.8    5
      0.76  0.04  2.3  0.092  15.0  54.0  0.9970  3.26  0.65  9.8    5
11.2  0.28  0.56  1.9  0.075  17.0  60.0  0.9980  3.16  0.58  9.8    6
7.4   0.70  0.00  1.9  0.076  11.0  34.0  0.9978  3.51  0.56  9.4    5
Name: fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality", dtype: int64

In [48]:
print("Mean of the X -->",np.mean(X))
print("Mode of Y -->", st.mode(Y))
print("Standard deviation of X -->", np.std(X))


Mean of the X --> fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"    5.636023
dtype: float64
Mode of Y --> ModeResult(mode=array([5]), count=array([681]))
Standard deviation of X --> fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"    0.807317
dtype: float64
